### ISSUE TITLE
Threading fails

### ISSUE THREAD

**Issue by carwash** [riksantikvarieambetet/SOCH-download-CLI#10]
Running a query on macOS, installed via pip, starts okay:
```
Validating arguments...
Fetching query data and calculating requirements...
Found 7398 results, they would be split over 15 requests/files
This program might use all the systems available CPUs(8)!
Would you like to proceed with the download? y/n
```

But then results in the following error when answering 'y':
```
Traceback (most recent call last):
  File "/Users/marcus/.pyenv/versions/3.6.7/bin/soch-download", line 186, in <module>
    start()
  File "/Users/marcus/.pyenv/versions/3.6.7/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/marcus/.pyenv/versions/3.6.7/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/marcus/.pyenv/versions/3.6.7/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/marcus/.pyenv/versions/3.6.7/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/marcus/.pyenv/versions/3.6.7/bin/soch-download", line 179, in start
    confirm(query, outdir)
  File "/Users/marcus/.pyenv/versions/3.6.7/bin/soch-download", line 91, in confirm
    return pre_fetch(query, required_n_requests, outdir)
  File "/Users/marcus/.pyenv/versions/3.6.7/bin/soch-download", line 62, in pre_fetch
    fetch(build_query(query, 500, start_record), start_record, outdir)
TypeError: do_task() takes 0 positional arguments but 3 were given
```
Tested with Python 3.6.7 and 3.7.1.

**Comment by carwash** [comment]
(Update: I get the same error on Debian with Python 3.5.)

**Comment by Abbe98** [comment]
@carwash could you share the command you are trying to execute?

**Comment by carwash** [comment]
Any and all queries I've tried result in the same error, but let's say for example:
`soch-download --action=query --query='serviceName="bbrp"' --outdir=xml --key=test`
…where the `./xml` directory definitely exists and is writeable, and `python -V` returns `Python 3.6.7` or `Python 3.7.1`. Starts fine, but when you hit 'y' to proceed, it dies.

**Comment by carwash** [comment]
I see that you've changed the title of this bug to something (presumably) more descriptive. With that in mind, is it possible that this isn't a bug at all, but that the versions of Python I have installed have simply been compiled without threading support?
